services:
  db:
    image: postgres:17.2-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  auth:
    image: quay.io/keycloak/keycloak:26.1.0
    restart: always
    ports:
      - "${KEYCLOAK_PORT}:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      REALM_ID: ${REALM_ID}
      REALM_NAME: ${REALM_NAME}
      
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    command: 
      - start-dev 
      - --import-realm
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: stopchocolate-backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth:8080/realms/${REALM_NAME}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth:8080/realms/${REALM_NAME}/protocol/openid-connect/certs
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_REALM: ${REALM_NAME}
      KEYCLOAK_CLIENT_ID: ${CLIENT_ID}
    depends_on:
      - db
      - auth