services:
  db:
    image: postgres:17.2-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"

  auth:
    image: quay.io/keycloak/keycloak:26.1.0
    restart: always
    ports:
      - "${KEYCLOAK_PORT}:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      REALM_ID: ${REALM_ID}
      REALM_NAME: ${REALM_NAME}

      ACCESS_TOKEN_LIFESPAN: ${ACCESS_TOKEN_LIFESPAN}

      EDIT_USERNAME_ALLOWED: ${EDIT_USERNAME_ALLOWED}

      MIN_PASSWORD_LENGTH: ${MIN_PASSWORD_LENGTH}
      MAX_PASSWORD_LENGTH: ${MAX_PASSWORD_LENGTH}
      MIN_DIGITS: ${MIN_DIGITS}
      MIN_UPPERCASE: ${MIN_UPPERCASE}
      MIN_LOWERCASE: ${MIN_LOWERCASE}
      MIN_SPECIAL_CHARS: ${MIN_SPECIAL_CHARS}

      SMTP_SERVER_HOST: ${SMTP_SERVER_HOST}
      SMTP_SERVER_PORT: ${SMTP_SERVER_PORT}
      SMTP_SERVER_USER: ${SMTP_SERVER_USER}
      SMTP_SERVER_PASSWORD: ${SMTP_SERVER_PASSWORD}
      SMTP_SERVER_SENDER_ADDRESS: ${SMTP_SERVER_SENDER_ADDRESS}
      SMTP_SERVER_SENDER_DISPLAY_NAME: ${SMTP_SERVER_SENDER_DISPLAY_NAME}
      
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    command: 
      - start-dev 
      - --import-realm
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: stopchocolate-backend:latest
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth:8080/realms/${REALM_NAME}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth:8080/realms/${REALM_NAME}/protocol/openid-connect/certs
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_MAIL_HOST: ${SMTP_SERVER_HOST}
      SPRING_MAIL_PORT: ${SMTP_SERVER_PORT}
      SPRING_MAIL_USERNAME: ${SMTP_SERVER_USER}
      SPRING_MAIL_PASSWORD: ${SMTP_SERVER_PASSWORD}
      SPRING_MAIL_SENDER_ADDRESS: ${SMTP_SERVER_SENDER_ADDRESS}
      SPRING_MAIL_SENDER_DISPLAY_NAME: ${SMTP_SERVER_SENDER_DISPLAY_NAME}

      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_REALM: ${REALM_NAME}
      KEYCLOAK_CLIENT_ID: ${CLIENT_ID}

      MIN_PASSWORD_LENGTH: ${MIN_PASSWORD_LENGTH}
      MAX_PASSWORD_LENGTH: ${MAX_PASSWORD_LENGTH}
      MIN_DIGITS: ${MIN_DIGITS}
      MIN_UPPERCASE: ${MIN_UPPERCASE}
      MIN_LOWERCASE: ${MIN_LOWERCASE}
      MIN_SPECIAL_CHARS: ${MIN_SPECIAL_CHARS}

      PASSWORD_RESET_TOKEN_EXPIRY_MINUTES: ${PASSWORD_RESET_TOKEN_EXPIRY_MINUTES}
    depends_on:
      - db
      - auth