spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: stopchocolate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${KEYCLOAK_PORT}/realms/${REALM_NAME}
          jwk-set-uri: http://localhost:${KEYCLOAK_PORT}/realms/${REALM_NAME}/protocol/openid-connect/certs

keycloak:
  admin-username: ${KEYCLOAK_ADMIN}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  realm: ${REALM_NAME}
  client-id: ${CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
